language: objective-c
osx_image: xcode8
env:
  - DESTINATION="OS=10.0,name=iPhone 6s" SCHEME="XLActionController" SDK=iphonesimulator10.0
before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -project XLActionController.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION"
    -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
  - xcodebuild -project Example.xcodeproj -scheme "Example" -sdk "$SDK" -destination "$DESTINATION"
      -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c
  - xcodebuild -project Example.xcodeproj -scheme "Example" -sdk "$SDK" -destination "$DESTINATION"
      -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty -c
